### ISSUE TITLE
Some Looks don't seem to operate properly.

### ISSUE THREAD

**Issue by berenyiaustin** [EaryChow/AgX#1]
Below I have renders in all 11 Look options for AgX. It seems that Very High Contrast, High Contrast, Medium High Contrast, Medium Low Contrast, Low Contrast, and Very Low Contrast are all producing identical results. Nothing changes when switching between those looks.

None
<img width="300" alt="Screenshot 2023-04-03 at 9 25 20 AM" src="https://user-images.githubusercontent.com/18562453/229556822-01864e2e-5c22-4d87-9f05-b1ae84cf06b0.png">
Punchy
<img width="300" alt="Screenshot 2023-04-03 at 9 25 32 AM" src="https://user-images.githubusercontent.com/18562453/229556833-efe2208d-854d-4e8d-b0a8-72b8c6033591.png">
Green Ink
<img width="300" alt="Screenshot 2023-04-03 at 9 25 58 AM" src="https://user-images.githubusercontent.com/18562453/229556837-71d16ef6-a86e-4431-962a-ad9aa0accd5f.png">
Greyscale
<img width="300" alt="Screenshot 2023-04-03 at 9 26 04 AM" src="https://user-images.githubusercontent.com/18562453/229556840-ee65c2a7-f3ae-4ed3-84a5-d41142e74e7c.png">
Very High Contrast
<img width="300" alt="Screenshot 2023-04-03 at 9 26 12 AM" src="https://user-images.githubusercontent.com/18562453/229556842-ddbd04ee-6d8e-485f-a9a9-ccc5cd045d16.png">
High Contrast
<img width="300" alt="Screenshot 2023-04-03 at 9 26 18 AM" src="https://user-images.githubusercontent.com/18562453/229556845-5f6064f7-dd7d-45cc-acb8-344cc3d6e38d.png">
Medium High Contrast
<img width="300" alt="Screenshot 2023-04-03 at 9 26 23 AM" src="https://user-images.githubusercontent.com/18562453/229556847-d080d293-2f6c-4ebc-8ec9-678016ef88df.png">
Base Contrast
<img width="300" alt="Screenshot 2023-04-03 at 9 26 30 AM" src="https://user-images.githubusercontent.com/18562453/229556851-78ec248a-2b53-4a51-b9a7-7510b7a911f2.png">
Medium Low Contrast
<img width="300" alt="Screenshot 2023-04-03 at 9 26 36 AM" src="https://user-images.githubusercontent.com/18562453/229556858-3be5bff0-5c48-4df5-958b-283d1b860093.png">
Low Contrast
<img width="300" alt="Screenshot 2023-04-03 at 9 26 46 AM" src="https://user-images.githubusercontent.com/18562453/229556861-a7733b4c-1a36-4f52-ae2d-240c1e96de1a.png">
Very Low Contrast
<img width="300" alt="Screenshot 2023-04-03 at 9 26 52 AM" src="https://user-images.githubusercontent.com/18562453/229556865-f90fb3f2-8a38-4ec9-aefa-6e1ce61d012c.png">

Display Device: sRGB
View Transform: AgX

Blender 3.6a, MacOS Apple Silicon

**Comment by Lt-knb** [comment]
I get the same behavior in 3.0.1

**Comment by EaryChow** [comment]
Strange, these looks should be supported after Blender 3.2, can you look at the system console and see if any error message pop up?

**Comment by berenyiaustin** [comment]
@EaryChow I get this error whenever I change to one of the Looks in question:

> Compile Error - Metal Shader Library (Stage: 2), error Error Domain=MTLLibraryErrorDomain Code=3 "program_source:2310:10: error: value of type 'bool __attribute__((ext_vector_type(3)))' (vector of 3 'bool' values) is not contextually convertible to 'bool'
>     if ( gamma != vec3(1., 1., 1.) )
>          ^~~~~~~~~~~~~~~~~~~~~~~~~
> " UserInfo={NSLocalizedDescription=program_source:2310:10: error: value of type 'bool __attribute__((ext_vector_type(3)))' (vector of 3 'bool' values) is not contextually convertible to 'bool'
>     if ( gamma != vec3(1., 1., 1.) )
>          ^~~~~~~~~~~~~~~~~~~~~~~~~
> }

**Comment by berenyiaustin** [comment]
I also received this message upon startup:

`Color management: scene view "Display Native" not found, setting default "Guard Rail".`

**Comment by EaryChow** [comment]
Strange, I thought the bug is already fixed : https://projects.blender.org/blender/blender/issues/96502

See if this config also produces the same error, if it does, then the Bug might still be there for Mac OS https://github.com/sobotka/AgX/tree/grading-primary-config

**Comment by berenyiaustin** [comment]
I received this same message with the config you referenced.

> Compile Error - Metal Shader Library (Stage: 2), error Error Domain=MTLLibraryErrorDomain Code=3 "program_source:2078:10: error: value of type 'bool __attribute__((ext_vector_type(3)))' (vector of 3 'bool' values) is not contextually convertible to 'bool'
    if ( gamma != vec3(1., 1., 1.) )
         ^~~~~~~~~~~~~~~~~~~~~~~~~
" UserInfo={NSLocalizedDescription=program_source:2078:10: error: value of type 'bool __attribute__((ext_vector_type(3)))' (vector of 3 'bool' values) is not contextually convertible to 'bool'
    if ( gamma != vec3(1., 1., 1.) )
         ^~~~~~~~~~~~~~~~~~~~~~~~~
}

**Comment by EaryChow** [comment]
Then it means it's either the OCIO upstream bug is still there or some bug in Blender regarding MacOS. MacOS throws shader error when using Grading Primary Transform.

**Comment by sobotka** [comment]
Someone has refreshed the upstream bug regarding the Metal compilations with the potential issue here?

**Comment by berenyiaustin** [comment]
@sobotka yes, the problem persists. Most of the Looks don’t work for me.

**Comment by sobotka** [comment]
If it is upstream at OpenColorIO, I am hoping folks have re-raised the issues?

**Comment by berenyiaustin** [comment]
@EaryChow @sobotka the problem is still around. Is the best place to report the issue on the OCIO GitHub project? Or is there a more efficient place to report it?

**Comment by EaryChow** [comment]
Yes,I believe so. I don't think there is anything else we can do if the bug is upstream.

**Comment by EaryChow** [comment]
Update, OCIO upstream says they already have the bug fixed, seems to be Blender using the older version where the bug was still there.
Reported to Blender Gitea: https://projects.blender.org/blender/blender/issues/109938

**Comment by EaryChow** [comment]
Seems like it's fixed : https://projects.blender.org/blender/blender/commit/259bfc45534af90a4d2b0a3d92a763114bb0ff22
@berenyiaustin Can you confirm on the latest 4.0 whether it's fixed?

**Comment by berenyiaustin** [comment]
Fixed!

**Comment by EaryChow** [comment]
Cool! Closing this then.
